# Generated by Django 4.2.2 on 2023-07-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiongrade',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='IN_PROGRESS', max_length=15),
        ),
    ]
