# Generated by Django 4.2.2 on 2023-06-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='submissions',
        ),
    ]
