# Generated by Django 4.2.2 on 2023-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grading', '0002_remove_task_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
