# Generated by Django 4.2.2 on 2023-07-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grading', '0003_alter_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='peer_grading.task'),
        ),
    ]
