# Generated by Django 4.2.3 on 2023-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grading', '0005_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gradingresult',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submissiongrade',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
